benefits-html
KoptevAnton/lloydjefferson.site pull request #7
Opened 2024-07-28 13:14 UTC by alex-stelmakh

2024-07-28 19:41 UTC, KoptevAnton requested changes
у коментарях все описано.

2024-07-28 19:41 UTC, KoptevAnton commented on src/partials/benefits.html
> +                <use href="../img/icons.svg#brush"></use>
у html файлах до зображень звертаємось через одну крапку.

2024-07-28 19:41 UTC, KoptevAnton commented on src/partials/benefits.html
>  <section class="benefits" id="benefits">
добав клас .section-margin

2024-07-28 20:15 UTC, alex-stelmakh commented on src/partials/benefits.html
>  <section class="benefits" id="benefits">
готово + додав css

2024-07-29 11:33 UTC, KoptevAnton approved these changes
Декілька  лишніх рядків можна видалити, у коментарях описав які саме.

2024-07-29 11:33 UTC, KoptevAnton commented on src/css/benefits.css
> +    letter-spacing: -0.02em;
Це від root приходит- можна видалити

2024-07-29 11:33 UTC, KoptevAnton commented on src/css/benefits.css
> +    letter-spacing: -0.02em;
це також лишнє

2024-07-29 11:33 UTC, merged